<?php

namespace LaravelMonitor\Support;

use Illuminate\Support\Carbon;
use Illuminate\Support\Str;

/**
 * One-time code proving the setup visitor has shell access to the server —
 * generated by `artisan monitor:setup-code`, verified against what they
 * paste into the setup page. Persisted as a PHP file under bootstrap/cache/
 * like {@see Settings}, since no monitor_users row exists yet to key off.
 */
class SetupCode
{
    protected const TTL_MINUTES = 10;

    /** Generates a fresh code, persists its hash, and returns the plain value to display. */
    public static function generate(): string
    {
        $plainCode = Str::upper(Str::random(4)).'-'.Str::upper(Str::random(4));

        static::write([
            'hash' => hash('sha256', $plainCode),
            'expires_at' => Carbon::now()->addMinutes(self::TTL_MINUTES)->toIso8601String(),
        ]);

        return $plainCode;
    }

    /** Whether $plainCode matches the currently stored code and hasn't expired. */
    public static function verify(string $plainCode): bool
    {
        $stored = static::read();

        if ($stored === null || Carbon::parse($stored['expires_at'])->isPast()) {
            return false;
        }

        return hash_equals($stored['hash'], hash('sha256', $plainCode));
    }

    /** Deletes the stored code once it's been used, so it can't be replayed. */
    public static function clear(): void
    {
        $path = static::path();

        if (is_file($path)) {
            @unlink($path);
        }
    }

    /**
     * @return array{hash: string, expires_at: string}|null
     */
    protected static function read(): ?array
    {
        $path = static::path();

        if (! is_file($path)) {
            return null;
        }

        $data = require $path;

        return is_array($data) && isset($data['hash'], $data['expires_at']) ? $data : null;
    }

    /**
     * Same atomic write-then-rename technique as {@see Settings::write()} —
     * a temp file plus rename() so a concurrent read never sees a
     * half-written file.
     *
     * @param  array{hash: string, expires_at: string}  $data
     */
    protected static function write(array $data): void
    {
        $path = static::path();
        $dir = dirname($path);

        if (! is_dir($dir)) {
            mkdir($dir, 0755, true);
        }

        $tmp = $path.'.'.uniqid('', true).'.tmp';
        file_put_contents($tmp, '<?php'.PHP_EOL.PHP_EOL.'return '.var_export($data, true).';'.PHP_EOL, LOCK_EX);
        rename($tmp, $path);
    }

    protected static function path(): string
    {
        return app()->bootstrapPath('cache/monitor-setup-code.php');
    }
}
